name = "ErgmDocs"
uuid = "00000000-0000-0000-0000-000000000001"
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ERGM = "7f6b9d0b-1c4e-4f5a-8b0c-7e6d5f4a3b21"

[compat]
Documenter = "1"
ERGM = "0.1"